version: "3.8"

services:
  db:
    image: mysql
    container_name: mysql_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root 
      MYSQL_PASSWORD: test
    volumes:
      - mysql_data:/var/lib/mysql
      - ./test.sql:/docker-entrypoint-initdb.d/test.sql
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    networks:
      - mysql-phpmyadmin
      

networks: 
  mysql-phpmyadmin:
    driver: bridge


volumes:
  mysql_data: