FROM node 
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD [ "node", "app.js"]

# commande création image
#docker build -t node-docker . --no-cache

# commande pour lancer container
# docker run --name docker-node -p 5000:3000 -d node-docker