FROM maven as builder

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline

COPY src ./src

RUN mvn package -DskipTests

FROM openjdk:11

COPY --from=builder /app/target/common-data-service.jar .

EXPOSE 9000

CMD ["java", "-jar", "common-data-service.jar"]

# commande création image
# docker build -t test-ecf-common-data . --no-cache

# commande pour lancer container
# docker run --name common-data-ecf-test -p 9050:9050 -d test-ecf-common-data